[package]
name = "query_driver"
version = "0.1.0"
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"

[dependencies]
query_system = { version = "0.1.0", path = "../query_system"}
interner = { version = "0.1.0", path = "../interner"}
salsa = "0.12"
walkdir = "2"