[workspace]
members = [
    "src/latin_lemmatizer",
    "src/latin_utilities",
    "src/query_system",
    "src/query_driver",
    "src/runner",
    "src/graphql_queries",
    "src/authors_chrono",
    "src/writers",
    "src/exporter",
]