[package]
name = "interner"
version = "0.1.0"
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"
description = "A crate for generic 1-1 invertible mappings"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "interner_benchmark"
harness = false