[package]
name = "latin_utilities"
version = "0.1.0"
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"

[dependencies]
unicode-normalization = "0.1.7"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "converter_benchmark"
harness = false