[package]
name = "authors"
version = "0.1.0"
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"

[dependencies]
interner = { version = "0.1.0", path = "../interner" }
sources = { version = "0.1.0", path = "../sources" }