[package]
name = "query_system"
version = "0.1.0"
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"
description = "High level description of the queries available"

[dependencies]
salsa = "0.12"
shrinkwraprs = "0.2"
latin_utilities = { version = "0.1", path = "../latin_utilities" }